name: ContentAPI
main: me.instrumentalityi.contentapi.paper.ContentAPIPlugin
version: 0.1.0
api-version: '1.21.4'
bootstrapper: me.instrumentalityi.contentapi.paper.ContentAPIBootstrap
loader: me.instrumentalityi.contentapi.paper.ContentAPILoader
dependencies:
  bootstrap:
    SteampunkLib:
      load: BEFORE
      required: true
      join-classpath: false
  server:
    SteampunkLib:
      load: BEFORE
      required: true
      join-classpath: true